version: '3.8'

services:
  # Virtual Stock Service
  virtual-stock-service:
    image: docker_virtual-stock-service:latest
    hostname: virtual-stock-service
    container_name: virtual-stock-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - custom_network
    external_links:
      - kafka:kafka
      - zookeeper:zookeeper
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # KBNT Log Service
  kbnt-log-service:
    image: kbnt-log-service:latest
    hostname: kbnt-log-service
    container_name: kbnt-log-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - custom_network
    external_links:
      - kafka:kafka
      - zookeeper:zookeeper
      - elasticsearch:elasticsearch
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# Define a custom network
networks:
  custom_network:
    driver: bridge
