version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-simple
    environment:
      POSTGRES_DB: virtualstock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped

  virtual-stock-service:
    build:
      context: ./microservices/virtual-stock-service
      dockerfile: Dockerfile
    container_name: virtual-stock-simple
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/virtualstock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8084:8084"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
