# =============================================================================
# API GATEWAY CONFIGURATION - PRODUCTION ENVIRONMENT
# =============================================================================
server:
  port: 8084
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: api-gateway
  profiles:
    active: prd
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Virtual Stock Service Route
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, prd
            - name: CircuitBreaker
              args:
                name: virtual-stock-service
                fallbackUri: forward:/fallback/virtual-stock
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 50
                redis-rate-limiter.burst-capacity: 100
                redis-rate-limiter.requested-tokens: 1
            
        # Log Producer Service Route  
        - id: log-producer-service
          uri: http://log-producer-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, prd
            - name: CircuitBreaker
              args:
                name: log-producer-service
                fallbackUri: forward:/fallback/log-producer
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 100
                redis-rate-limiter.burst-capacity: 200
                redis-rate-limiter.requested-tokens: 1
            
        # KBNT Log Service Route
        - id: kbnt-log-service
          uri: http://kbnt-log-service:8081
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, prd
            - name: CircuitBreaker
              args:
                name: kbnt-log-service
                fallbackUri: forward:/fallback/kbnt-logs
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 30
                redis-rate-limiter.burst-capacity: 60
                redis-rate-limiter.requested-tokens: 1

      # Global CORS Configuration - Production Restricted
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "https://app.kbnt.com"
              - "https://www.kbnt.com"
              - "https://dashboard.kbnt.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: 
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
              - "Accept"
              - "Origin"
            allowCredentials: true
            maxAge: 7200

# Management Endpoints - Production Security
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
    info:
      enabled: true
  server:
    port: 9080
  security:
    enabled: true

# Logging Configuration - Production Optimized
logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.web.reactive: ERROR
    reactor.netty: ERROR
    com.kbnt: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/api-gateway-prd.log
    max-size: 100MB
    max-history: 30

# Circuit Breaker Configuration - Production Grade
resilience4j:
  circuitbreaker:
    instances:
      virtual-stock-service:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60000
        sliding-window-size: 200
        minimum-number-of-calls: 50
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 3000
        permitted-number-of-calls-in-half-open-state: 10
      log-producer-service:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60000
        sliding-window-size: 200
        minimum-number-of-calls: 50
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 3000
        permitted-number-of-calls-in-half-open-state: 10
      kbnt-log-service:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60000
        sliding-window-size: 200
        minimum-number-of-calls: 50
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 3000
  retry:
    instances:
      virtual-stock-service:
        max-attempts: 3
        wait-duration: 3000
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
      log-producer-service:
        max-attempts: 3
        wait-duration: 2000
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
  ratelimiter:
    instances:
      default:
        limit-for-period: 1000
        limit-refresh-period: 60s
        timeout-duration: 10s
