# =============================================================================
# API GATEWAY CONFIGURATION - DEFAULT/DOCKER ENVIRONMENT
# =============================================================================
server:
  port: 8084

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Virtual Stock Service Route
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, docker
            
        # Log Producer Service Route
        - id: log-producer-service
          uri: http://log-producer-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, docker
            
        # KBNT Log Service Route
        - id: kbnt-log-service
          uri: http://kbnt-log-service:8081
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, docker
            
      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
        - id: log-producer-service
          uri: http://log-producer-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
        - id: kbnt-log-service
          uri: http://kbnt-log-service:8081
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
