# =============================================================================
# API GATEWAY CONFIGURATION - DEVELOPMENT ENVIRONMENT
# =============================================================================
server:
  port: 8084

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Virtual Stock Service Route
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, dev
            - name: CircuitBreaker
              args:
                name: virtual-stock-service
                fallbackUri: forward:/fallback/virtual-stock
            
        # Log Producer Service Route  
        - id: log-producer-service
          uri: http://log-producer-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, dev
            - name: CircuitBreaker
              args:
                name: log-producer-service
                fallbackUri: forward:/fallback/log-producer
            
        # KBNT Log Service Route
        - id: kbnt-log-service
          uri: http://kbnt-log-service:8081
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - AddRequestHeader=X-Environment, dev
            
        # Health Check Aggregator
        - id: health-aggregator
          uri: http://api-gateway:9080
          predicates:
            - Path=/api/v1/health/**
          filters:
            - StripPrefix=2

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "https://dev-frontend.kbnt.com"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    gateway:
      enabled: true
  server:
    port: 9080

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: WARN
    reactor.netty: WARN
    com.kbnt: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/api-gateway-dev.log

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      virtual-stock-service:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 60000
        sliding-window-size: 20
        minimum-number-of-calls: 10
      log-producer-service:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 60000
        sliding-window-size: 20
        minimum-number-of-calls: 10
  retry:
    instances:
      virtual-stock-service:
        max-attempts: 3
        wait-duration: 1000
      log-producer-service:
        max-attempts: 3
        wait-duration: 1000
